# Generated by Django 2.1.1 on 2018-10-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20)),
                ('lesson', models.ForeignKey(db_column='lessonid', on_delete=None, to='dictation.Lesson')),
            ],
            options={
                'db_table': 'lw_word',
            },
        ),
    ]
