# Generated by Django 2.1.1 on 2018-10-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0002_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicename', models.CharField(max_length=20)),
                ('choicevalue', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lw_choiceselected',
            },
        ),
    ]
