# Generated by Django 2.1.1 on 2018-11-13 22:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0003_choiceselected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='choicetype', default='time', max_length=20)),
                ('name', models.CharField(db_column='choicename', max_length=50)),
                ('condition', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'lw_choice',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(db_column='testid', primary_key=True, serialize=False)),
                ('testtime', models.DateTimeField(auto_now_add=True)),
                ('testname', models.CharField(max_length=50)),
                ('testcontent', models.CharField(max_length=200, null=True)),
                ('level', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lw_test',
            },
            managers=[
                ('tests', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TestWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong', models.BooleanField(db_column='wrong', default=False)),
                ('test', models.ForeignKey(db_column='testid', on_delete=None, to='dictation.Test')),
                ('word', models.ForeignKey(db_column='wordid', on_delete=None, to='dictation.Word')),
            ],
            options={
                'db_table': 'lw_testwords',
            },
        ),
        migrations.RenameField(
            model_name='book',
            old_name='grade',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='press',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unitname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='choiceselected',
            name='choicecode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(db_column='bookname', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_column='grade', max_length=20),
        ),
        migrations.AlterField(
            model_name='choiceselected',
            name='choicename',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='choiceselected',
            name='choicevalue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='name',
            field=models.CharField(db_column='pname', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(db_column='unitname', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='book',
            field=models.ForeignKey(db_column='bookid', on_delete=None, to='dictation.Book'),
        ),
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(db_column='lessonid', null=True, on_delete=None, to='dictation.Lesson'),
        ),
        migrations.AddField(
            model_name='test',
            name='press',
            field=models.ForeignKey(db_column='pressid', on_delete=None, to='dictation.Press'),
        ),
        migrations.AddField(
            model_name='test',
            name='unit',
            field=models.ForeignKey(db_column='unitid', null=True, on_delete=None, to='dictation.Unit'),
        ),
    ]
