# Generated by Django 2.1.1 on 2018-11-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0004_auto_20181113_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='lesson',
            field=models.ForeignKey(db_column='lessonid', on_delete=django.db.models.deletion.CASCADE, to='dictation.Lesson'),
        ),
    ]
